### ISSUE TITLE
Disconnects shortly after starting

### ISSUE THREAD

**Issue by macjeff** [simplextech/udi-poly-linktap#4]
Today I worked with you and ran a few updates.

I was running 0.1.7 and had no issues all day updating.

I stopped the server, updated to 0.1.8, and then restarted it.  I watched it connect and then about 2 seconds later disconnect.

I then totally deleted the nodeserver from Polisy and ISY.  I even uninstalled it and then reinstalled it and then added it back.  Everything added and connected fine and my nodes showed up in ISY and worked.

then as a test I hit restart and same thing.  Connected and then disconnected. 

Just as a test I tried to restart every other nodeserver and they all worked fine.  So I tried one more time to uninstall and reinstall and of course as soon as I hit restart the same thing.

I also rebooted the ISY and it restarted fine the first time but tried a second and would not restart.  So this issue could have started with 0.1.7 because I never restarted that one after initial install.  I did restart the 0.1.4 version a few times.

No luck with polisy reboot either so I am going to reinstall and leave it for now.

I attached logs and a video of the issue
[Screen Recording 2020-05-25 at 10.26.48 PM.zip](https://github.com/simplextech/udi-poly-linktap/files/4679587/Screen.Recording.2020-05-25.at.10.26.48.PM.zip)

**Comment by macjeff** [comment]
looks like logs did not attach
[LinkTap_logs_2020-5-25_222748.zip](https://github.com/simplextech/udi-poly-linktap/files/4679670/LinkTap_logs_2020-5-25_222748.zip)

**Comment by simplextech** [comment]
PLEASE do not attach screen recordings.  

If you installed, or did any stop/start operation within 5 minutes then you are hitting the LinkTap 5 minute rate limit and the nodeserver is shutting down.

**Comment by simplextech** [comment]
2020-05-25 22:27:35,019 NodeServer polyinterface      INFO     LinkTap:get_link_tap_devices: get_link_tap_devices: The minimum interval of calling this API is 5 minutes.
2020-05-25 22:27:35,021 NodeServer polyinterface      INFO     LinkTap:start: start: Failed to start due to API error.  Shutting down.

On Start the Nodeserver pulls all data from LinkTap to setup the devices.  There is a 5 minute rate limit imposed by LinkTap.  If you do a stop/start or re-install or anything you must wait in between doing this.
